/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 20/11/2010, 21:32:20
 */

package guiDesktop;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Tiago Brasileiro
 */
public class FramePrincipal extends javax.swing.JFrame {

    /** Creates new form FramePrincipal */
    public FramePrincipal(String idSessao) {
        initComponents();

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception ex) {
            setDefaultLookAndFeelDecorated(true);
        }
        SwingUtilities.updateComponentTreeUI(this);

        setVisible(true);
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Blogão");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoMeusBlogs = new javax.swing.JToggleButton();
        botaoEditaPerfil = new javax.swing.JToggleButton();
        botaoLogout = new javax.swing.JToggleButton();
        botaoCriarBlogs = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoMeusBlogs.setText("Meus Blogs");
        botaoMeusBlogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMeusBlogsActionPerformed(evt);
            }
        });

        botaoEditaPerfil.setText("Editar Perfil");
        botaoEditaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditaPerfilActionPerformed(evt);
            }
        });

        botaoLogout.setText("Logout");
        botaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogoutActionPerformed(evt);
            }
        });

        botaoCriarBlogs.setText("Criar Blog");
        botaoCriarBlogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarBlogsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoMeusBlogs, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(botaoCriarBlogs, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(botaoEditaPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(629, 629, 629))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(botaoMeusBlogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCriarBlogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEditaPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoLogout)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogoutActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botaoLogoutActionPerformed

    private void botaoEditaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditaPerfilActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botaoEditaPerfilActionPerformed

    private void botaoMeusBlogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMeusBlogsActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botaoMeusBlogsActionPerformed

    private void botaoCriarBlogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarBlogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCriarBlogsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCriarBlogs;
    private javax.swing.JToggleButton botaoEditaPerfil;
    private javax.swing.JToggleButton botaoLogout;
    private javax.swing.JToggleButton botaoMeusBlogs;
    // End of variables declaration//GEN-END:variables

}
